name: Deploy React Web Demo

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/flutter_web_demo.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: src
