name: Build Flutter Web Demo

on:
  push:
    paths:
      - 'flutter_demo/**'
      - '.github/workflows/flutter_web_demo.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
        working-directory: flutter_demo
      - name: Build web demo
        run: flutter build web -o ../docs
        working-directory: flutter_demo
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

